settings:
  username: "phixion"
  commit_msg: "âš¡update this repo's README.md with github statistics"
  max_lines: 5
  readme_file: "./README.md"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+00:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_username: "readme-bot"
messages:
  comments: "Commented on {ID} in {REPO}"
  issue_opened: "Opened issue {ID} in {REPO}"
  issue_closed: "Closed issue {ID} in {REPO}"
  pr_opened: "Opened PR {ID} in {REPO}"
  pr_closed: "Closed PR {ID} in {REPO}"
  pr_merged: " Merged PR {ID} in {REPO}"
  create_repo: "Created new repository {REPO}"
  fork_repo: "Forked {FORK} from {REPO}"
  wiki_create: "Created new wiki page {WIKI} in {REPO}"
  added_member: "Became collaborator on {REPO}"
  changes_approved: "Approved {ID} in {REPO}"
  changes_requested: "Requested changes in {ID} in {REPO}"
  new_release: "Released {ID} in {REPO}"
  new_star: "Starred {REPO}"
